### ISSUE TITLE
Multi-column layout for authors

### ISSUE THREAD

**Issue by gongcastro** [mikemahoney218/quarto-arxiv#12]
I was wandering if it could be possible to include an option in the YAML header for a multi-column layout for the authors block ([example](https://www.overleaf.com/latex/templates/arxiv-and-prime-ai-style-template/qdnhqytdqzsc)), as opposed to the one-column layout currently implemented. I figured out I had to change `\\\\\\` for `\And` in [title.tex](partials/title.tex) like this:

```tex
# one-column layout
\author{${ by-author:_authors.tex()[\And] }}

# multicolumn-layout
\author{${ by-author:_authors.tex()[\And] }}
```

Maybe something like this? (I could not get it to work, though):

```yaml
arxiv-pdf:
  authors-onecolumn: true
```
```tex
\author{${ by-author:_authors.tex()[$if(authors-onecolumn)\\\\\\$else$\And$endif$] }}
```

I whish I could be of more help implementing this (I'm a bit out of my depth with Pandoc), but I think this option would be handy to avoid devoting more than one page for the author section in papers with > 4 authors.

PS: Thanks a lot for this template, it has already saved me a lot of time formatting!

**Comment by mikemahoney218** [comment]
Thanks! This should be fixed now via the new `authorcols` option (I'll release a new version of the template momentarily).
