### ISSUE TITLE
math bold letters are not bolded in the arxiv-pdf

### ISSUE THREAD

**Issue by huizezhang-sherry** [mikemahoney218/quarto-arxiv#5]
Thanks for the arxiv template! I'm trying to use Math bold letters in the template qmd with the following: 

> This is what rendered by `\mathbf{v}`: $\mathbf{v}$

but the `v` is not bolded in the rendered pdf: 

<img width="1004" alt="Screen Shot 2022-11-21 at 2 28 11 pm" src="https://user-images.githubusercontent.com/36781502/202959708-5bc4138a-3000-4122-ba5e-e17c56071650.png">

Maybe I'm missing something obvious here!

**Comment by mikemahoney218** [comment]
Hmm, not 100% sure what's going on here. That said, any chance the `\symbf{}` command works?

![image](https://user-images.githubusercontent.com/38229299/203074116-889f2cfc-0c96-4b80-90e8-521273dd25d0.png)

Based off a thread in [the Pandoc discussion group](https://groups.google.com/g/pandoc-discuss/c/gjG9wVbnps8/m/XJ9F5kKLBgAJ), if you like the output from `\symbf` then I think that's the ideal way to do this -- I _think_ (but am not sure) that `\mathbf` has challenges with certain latex rendering engines.

**Comment by mikemahoney218** [comment]
(Also: hi Sherry! Not sure if you remember, but I believe we spoke in the same timeslot at useR 2021 -- hope you're well :smile: )

**Comment by mikemahoney218** [comment]
One last note: I think (based off this StackExchange: https://tex.stackexchange.com/a/38631 ) that the core issue comes from the `unicode-math` package, which is attached

**Comment by huizezhang-sherry** [comment]
`\symbf{}` is good enough for me at this stage. 

I reckon one issue with `\mathbf{}` is that Latin Modern Math doesn't have a bold typeface.

And yes! I remember you and I think we both speak at useR 2022 as well!

**Comment by mikemahoney218** [comment]
Ah, that's it! In version 0.2.1 (which I'm about to release), `\mathbf` now works as expected:

![image](https://user-images.githubusercontent.com/38229299/203313672-a6d246f3-dd40-4789-a4ec-e294c28389c9.png)

Thanks for pointing out the missing bold typeface -- wouldn't have caught that.

**Comment by Doktorandahl** [comment]
Hi Mike,
Thanks so much for this quarto template, it's really great and easy to use!

I'm still having problem with boldface math letters though, specifically greek letters. I've tried a wide range of combinations of options with \mathbf{\beta}, \symbf{\beta}, adding the bm package to the prelude and \bm{\beta} etc, but can't seem to find a solution. Any suggestions?

**Comment by mikemahoney218** [comment]
@Doktorandahl -- have you tried using `pmb`? I also seem to get a (subtly) bolded output from `\symbf`:

![image](https://github.com/mikemahoney218/quarto-arxiv/assets/38229299/1cacbc8d-764e-4cf4-b359-14b9d4c2822b)

**Comment by Doktorandahl** [comment]
Thanks Mike, \pmb{} worked
